### ISSUE TITLE
Curious about uvcdynctrl usage

### ISSUE THREAD

**Issue by virtuald** [ligerbots/VisionServer#3]
Referring to [this line in your startup script](https://github.com/ligerbots/VisionServer/blob/b4f0af7db08707ece7decb6722c0089cf1655f2f/server/start_server#L40)...  pretty sure cscore should be able to get/set any property that uvcdynctrl can set, since they'll end up using the same API...  [getProperty](https://robotpy.readthedocs.io/projects/cscore/en/latest/objects.html?highlight=getProperty#cscore.VideoSource.getProperty) on the sink followed by a set would do it. The [cscore settings example](https://github.com/robotpy/robotpy-cscore/blob/master/examples/settings.py) shows how to do this.

Is that something you tried and it didn't work? Or just lack of documentation so you didn't realize the functionality was there?

**Comment by prensing** [comment]
I would have to dig, but what I remember is that the focus parameters were not exposed in cscore (Python? C++?). I kind of remember digging around and could not find those "enums". Maybe if I had passed through the right integer, it would have worked.

I will try to see if it is still a problem.

**Comment by prensing** [comment]
Actually, it may be that I did not find out about getProperty. I use the direct routines like "setResolution", but not "setProperty()". 

However, I think it is missing from the documentation? I cannot find it in readthedocs. (And since CScore is mostly all compiled C++, it is not easy to browse the Python.)

**Comment by virtuald** [comment]
The API is a bit weird, you have to retrieve a property object, then you use that to set it. Probably could use more examples. See https://github.com/robotpy/robotpy-cscore/blob/2590274ca4e9ef852093152be34bde4e56d027f3/examples/settings.py#L66 for the example.
